// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: author_queries.sql

package playground

import (
	"context"
)

const findAllAuthors = `-- name: FindAllAuthors :many
SELECT id, name FROM authors
`

func (q *Queries) FindAllAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, findAllAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuthors = `-- name: InsertAuthors :execlastid
INSERT INTO authors(name)
VALUES (?)
`

func (q *Queries) InsertAuthors(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAuthors, name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
