// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package playground

import ()

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	AuthorID int64  `json:"author_id"`
}
