// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package playground

import ()

type Author struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Book struct {
	ID       int64  `db:"id" json:"id"`
	Title    string `db:"title" json:"title"`
	AuthorID int64  `db:"author_id" json:"author_id"`
}
