// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package playground

import ()

type Author struct {
	// primary key
	ID int64 `db:"id" json:"id"`
	// author name
	Name string `db:"name" json:"name"`
}

type Book struct {
	// primary key
	ID int64 `db:"id" json:"id"`
	// book title
	Title string `db:"title" json:"title"`
	// book's author reference ID
	AuthorID int64 `db:"author_id" json:"author_id"`
}
