// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"database/sql"
	"github.com/google/wire"
	"go-chi-sqlc-template/adapter/db"
	"go-chi-sqlc-template/adapter/db/playground"
)

// Injectors from wire.go:

func initApp(ctx context.Context, dsn string) (*App, error) {
	sqlDB, err := db.OpenMySQL(ctx, dsn)
	if err != nil {
		return nil, err
	}
	queries := playground.New(sqlDB)
	app := &App{
		queries: queries,
	}
	return app, nil
}

// wire.go:

var (
	queryProvider = wire.NewSet(db.OpenMySQL, wire.Bind(new(playground.DBTX), new(*sql.DB)), playground.New)
)
